name: 'Validate the version of the package'
description: 'Checks that the current version of package is correct relative to the last version tag'
inputs:
  package_type:
    description: 'The type of package to be published'
    required: true
  comparison:
    description: 'The comparison to be done. A string with a value in { >, <, =, <=, >= }'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get last release version
      id: last-release-version
      uses: actions-ecosystem/action-get-latest-tag@v1
      with:
        semver_only: true

    - name: Get version
      id: this-version
      uses: mt-actions/get-version@v1.0.0
      with:
        package_type: ${{ inputs.package_type }}

    - name: Assert version
      uses: jackbilestech/semver-compare@1.0.4
      with:
        operator: ${{ inputs.comparison }}
        head: ${{ steps.this-version.outputs.version }}
        base: ${{ steps.last-release-version.outputs.tag }}
